"""Added Title

Revision ID: 5fcbec988b9e
Revises: 528dd50afd65
Create Date: 2022-05-29 16:05:33.894119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcbec988b9e'
down_revision = '528dd50afd65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'title')
    # ### end Alembic commands ###
