"""Added Not Null on Title

Revision ID: 619b93b8cead
Revises: 5fcbec988b9e
Create Date: 2022-05-29 16:08:04.378371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619b93b8cead'
down_revision = '5fcbec988b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
